void IHCAN(double *px,
           double cf,
           int nrep,
           double tdres,
           int totalstim,
           double cohc,
           double cihc,
           int species,
           double bandwidth_scale_factor,
           double IhcLowPass_cutoff,
           double IhcLowPass_order,
           double *ihcout);
