void SingleAN(double *px,
              double cf,
              int nrep,
              double tdres,
              int totalstim,
              double noiseType,
              double implnt,
              double spont,
              double tabs,
              double trel,
              double *meanrate,
              double *varrate,
              double *psth,
              double *synout,
              double *trd_vector,
              double *trel_vector);

double Synapse(double *ihcout,
               double tdres,
               double cf,
               int totalstim,
               int nrep,
               double spont,
               double noiseType,
               double implnt,
               double sampFreq,
               double *synout);

int SpikeGenerator(double *synout,
                   double tdres,
                   double t_rd_rest,
                   double t_rd_init,
                   double tau,
                   double t_rd_jump,
                   int nSites,
                   double tabs,
                   double trel,
                   double spont,
                   int totalstim,
                   int nrep,
                   double total_mean_rate,
                   long MaxArraySizeSpikes,
                   double *sptime,
                   double *trd_vector);
