/* Generated by Cython 0.29.8 */

#ifndef __PYX_HAVE__test_by_mark
#define __PYX_HAVE__test_by_mark


#ifndef __PYX_HAVE_API__test_by_mark

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double *generate_random_numbers(long);
__PYX_EXTERN_C double *decimate(int, double *, int);
__PYX_EXTERN_C double *ffGn(int, double, double, double, double);

#endif /* !__PYX_HAVE_API__test_by_mark */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inittest_by_mark(void);
#else
PyMODINIT_FUNC PyInit_test_by_mark(void);
#endif

#endif /* !__PYX_HAVE__test_by_mark */
